version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=supersecretjwtkey
      - DATABASE_URL=sqlite:///webvulscan.db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  zap:
    image: owasp/zap2docker-weekly
    ports:
      - "8080:8080"
    environment:
      - ZAP_PORT=8080
    command: ["zap.sh", "-daemon", "-port", "8080", "-host", "0.0.0.0"]
